Add UnionFind
ojeveryday/AlgoWiki pull request #21
Opened 2020-05-16 03:34 UTC by OneDirection9

2020-05-16 23:36 UTC, liweiwei1419 requested changes
我的修改意见就是这样，可以看出作者很用心、很认真地编写教程，感谢作者的付出。

2020-05-16 23:36 UTC, liweiwei1419 commented on UnionFind/01-introduction.md
> +并查集（Disjoint set，Union-Find）是一种树形数据结构，支持两种操作：
是一种建立在数组上的树形结构，树的特点是孩子节点指向父亲节点。

建议：用最简单的一句话先说清楚「并查集」能够干嘛。

例如：

并查集是一种高效处理不相交集合的连接与查询操作的数据结构，它是一种建立在数组上的树（森林）形结构。（个人意见，可能概括还不够准确，仅供参考。）

2020-05-16 23:36 UTC, liweiwei1419 commented on UnionFind/01-introduction.md
> +并查集的一个重要思想是，**用集合中的某一个元素代表整个集合**。
这句话放在解释「合并」与「查找」之前会更好：

并查集的一种高效实现是：使用树的根节点表示一个集合，即：只要两个元素的根节点相同，就视为属于同一个集合。使用树的根节点表示一个集合的方法，称之为「代表元」法。

2020-05-16 23:36 UTC, liweiwei1419 commented on UnionFind/01-introduction.md
> +除以之外一般还需要**初始化**操作，将每个元素所在的集合初始化为其自身。
除「此」之外。这句话在这里可以省略，我个人感觉在概述部分，读者未必需要知道这个特别细节的地方。

2020-05-16 23:36 UTC, liweiwei1419 commented on UnionFind/01-introduction.md
> +1. 最小生成树：Kruskal 算法
如果不是体现必要的顺序关系，可以使用「无序列表」。

这样二级列表可能会好看一点，照理说二级列表需要显示成类似 3.1 、3.2 这样的编号。

2020-05-16 23:36 UTC, liweiwei1419 commented on UnionFind/01-introduction.md
> +1. 不支持 split 操作：任何节点一旦成为其他节点的子节点后，将永远不可能再成为树根。
能用中文解释就先中文解释，加括弧英文补充专有名字。

不支持集合拆分（split）操作。下同：集合必须是不相交（disjoint）的

2020-05-16 23:36 UTC, liweiwei1419 commented on UnionFind/01-introduction.md
> +
「路径压缩」和「按秩合并」这两个「并查集」的优化技巧我个人觉得应该是属于同一个地位的。这里引入「进阶」和「高级」的概念可能不是很合适。

一种建议的说法是：

+ 基本版本的并查集实现仅仅能够完成任务，但是效率较低，原因是某些集合在合并的过程中可能造成树的深度过大。针对这个问题，在真正应用并查集的时候，需要使用一些优化的操作；
+ 「路径压缩」和「按秩合并」是两种常见的并查集优化操作，可以同时使用，但一般而言，使用其一就能保证很不错的时间效率。

2020-05-16 23:36 UTC, liweiwei1419 commented on UnionFind/02-template-1.md
> +一道典型的并查集应用的题目：[「洛谷」P 1551 亲戚](https://www.luogu.com.cn/problem/P1551)。
可能部分读者对于「洛谷」不是很熟悉（仅仅只是在要求编写输入输出上）。在选择例题的时候，同类问题优先选择 LeetCode 的问题可能是新手友好的。

这个题在 LeetCode 上对应是第 547 题：朋友圈。可以把「洛谷」上的问题作为补充练习。

2020-05-16 23:36 UTC, liweiwei1419 commented on UnionFind/02-template-1.md
> +
这里补充一句：我们通过一个非常典型的问题，向大家介绍并查集的实现原理，这道问题是「洛谷」上第 题（LeetCode 上第 题）。

2020-05-16 23:36 UTC, liweiwei1419 commented on UnionFind/02-template-1.md
> +先展示代码，细节分析在代码之后。
代码通常来说放在后面，对这个知识点不太熟悉的同学需要先知道思想，然后才是示例代码。

代码是补充细节说明用的，前面说思想。

2020-05-16 23:36 UTC, liweiwei1419 commented on UnionFind/02-template-1.md
> +        p = vector<int>(n, 0);
这里 `p` 建议写成 `parent` 突出算法思想。

2020-05-16 23:36 UTC, liweiwei1419 commented on UnionFind/02-template-1.md
> +
查找代表元的 `Find` 方法或许写成循环的版本会更好理解一点。

2020-05-16 23:36 UTC, liweiwei1419 commented on UnionFind/03-template-2.md
> +依次对 `1 2`，`1 5`，`3 4`，`5 2` 进行合并之后得到：
依次对 `1 2`，`1 5`，`3 4`，`5 2` 进行合并，这个描述读起来不是顺，想一想怎么写会比较好。

直接写成 `Union(1, 2)` 可读性或许更好一点。

2020-05-16 23:36 UTC, liweiwei1419 commented on UnionFind/02-template-1.md
> +每次查询节点 `1` 的时候都需要遍历整个「树」，所以 `Find` 函数最坏时间复杂度是：**`O(n)`**，`n` 为节点数。
时间复杂度和空间复杂度的表达应该使用数学符号。

2020-05-16 23:36 UTC, liweiwei1419 commented on UnionFind/03-template-2.md
> +采用**路径压缩（Path Compression）**进行优化。路径压缩会在执行 `Find(x)` 函数时，将 `x` 到根节点的所有节点全部指向根。这样使得树变得扁平，缩短下次查询时的查找路径。
这里最好配图说明「路径压缩」之后的树结构与原始树结构的等价性。由于我们用的是代表元法，树的形态并不重要，路径压缩保证了同一棵树下的根结点不变，高度更小的树能够有更好的查询性能。

2020-05-16 23:36 UTC, liweiwei1419 commented on UnionFind/03-template-2.md
> +            // 非集合代表元素，将其直接指向根节点，达到路径压缩的目的
这里没有那么「直接」，是因为递归调用返回的时候，才把沿途经过的结点指向了根结点。

2020-05-16 23:36 UTC, liweiwei1419 commented on UnionFind/03-template-2.md
> +理论上，执行 $m$ 次 `Find` 操作，$n-1$ 次 `Union` 操作的时间复杂度是 **$O(mlogn)$**，其中 $m \geq n $。
$O(mlogn)$，这里 log 是专有数学符号，前面要加上 \ 和空格 ，后面要加上空格，例如 $O(m \log n)$

2020-05-16 23:36 UTC, liweiwei1419 commented on UnionFind/03-template-2.md
> +# 进阶模板
「进阶」模板和「高级」模板，这样的概念可能需要修改（在之前的部分也介绍过了）。

大致想和读者说明的一点是：基础版本的「并查集」是低效的，很多时候提交到 oj 上得不到通过。

2020-05-16 23:36 UTC, liweiwei1419 commented on UnionFind/03-template-2.md
> +路径压缩只优化 `x` 节点到其根节点的路径，而 **`x` 子节点的路径不会被优化**。
这个细节强调得特别棒！

2020-05-16 23:36 UTC, liweiwei1419 commented on UnionFind/04-template-3.md
> +
这个提法或许不是很恰当，想一想怎么说会更好。很多时候，维护树的最大深度是更合理的，即使我们所维护的「最大深度」的值不一定准确，但这个值仍然具有参考价值（这句话放在这里说可能读者会比较疑惑，可以考虑后移）。

2020-05-16 23:36 UTC, liweiwei1419 commented on UnionFind/04-template-3.md
> +        r = vector<int>(n, 1);
`r` 依然建议写成 `rank`。

2020-05-16 23:36 UTC, liweiwei1419 commented on UnionFind/04-template-3.md
> +理论上，路径压缩+按秩合并，执行 $m$ 次 `Find` 操作，$n-1$ 次 `Union` 操作的时间复杂度是 **$O(m \space \alpha (m, n))$**，其中 $m \geq n $，$\alpha(m,n)$ 是反阿克曼函数。
`+` 符号前后应空 1 格。并且这种写法作为书面语不规范，建议写成：

理论上，同时使用「路径压缩」与「按秩合并」，...

2020-05-16 23:36 UTC, liweiwei1419 commented on UnionFind/04-template-3.md
> +**Theorem.** *[Tarjan 1975]* Link-by-size with path compression performs any intermixed sequence of $m \geq n$ FIND and $n-1$ UNION operations in $O(m \space \alpha(m, n))$ time, where $\alpha(m, n)$
这里最好提示读者，反阿克曼函数的结论知道即可，具体的数学细节感兴趣的读者可以查询下面给出的论文。

结论：反阿克曼函数是一个渐进复杂度很低的函数，通常可以认为是常数级别的时间复杂度。

2020-05-16 23:36 UTC, liweiwei1419 commented on UnionFind/05-examples.md
> +        if(!p.count(x)) p[x] = x, ++islands;
这里 `++isLands` 在不在 `if` 包含的循环体内，可能会让读者产生疑惑。下面 `Union` 函数也有同样的问题。

我们写教程以语义清晰为先，并且除了极其特别的地方（例如 `for` 循环遍历），遵循一行代码只做一件事情的原则，应该杜绝竞赛式提交给机器阅读的代码写法。

括号和换行能写上就不应该省略，这是我们在编写教程的  README 文档里提示过的，请保持这个原则。

2020-05-16 23:36 UTC, liweiwei1419 commented on UnionFind/05-examples.md
> +[Count the Number of Islands O(N)](https://leetcode.com/problems/most-stones-removed-with-same-row-or-column/discuss/197668/Count-the-Number-of-Islands-O(N))
下面这条意见仅供参考：

在作者本人能够解释清楚这个例题的思路的前提下，可以不再引入他人的写法和解释。除非是引用原话和原图。建议引用已经发表的作品，例如前面解释复杂度之类的补充说明。

选取例题的原则应该是思想典型和重点突出、可以举一反三的。并查集的问题的思路通常需要画图解释清楚。这道题我个人感觉作者还可以写得更好。

我看了一下引用的资料和下面的评论，大概率上不是新手友好的（并且还是英文的），不太符合我们这个教程的读者的定位，不建议作为参考资料。

2020-05-16 23:36 UTC, liweiwei1419 commented on UnionFind/05-examples.md
> +介绍上面两个例题的目的在于：
这里总结很不错！

2020-05-16 23:36 UTC, liweiwei1419 commented on UnionFind/06-practices.md
> +# 练习
建议分类标准加上「带权并查集」和「不带权并查集」。

然后带上「基础」（「必做」）和「困难」（选做）等提示标签，或者由易到难列出，对读者更友好。

2020-05-25 08:11 UTC, OneDirection9 commented on UnionFind/02-template-1.md
> +一道典型的并查集应用的题目：[「洛谷」P 1551 亲戚](https://www.luogu.com.cn/problem/P1551)。
个人感觉「朋友圈」这道题目好像没有洛谷的这道题目直接。

2020-06-21 12:08 UTC, closed without merging