Update UnionFind
ojeveryday/AlgoWiki pull request #30
Opened 2020-06-21 12:09 UTC by OneDirection9

2020-06-25 08:42 UTC, liweiwei1419 commented on UnionFind/01-introduction.md
> +并查集（Disjoint set，Union-Find）是一种用来管理元素分组情况的数据结构。并查集的一种高效实现是：**使用树的根节点表示一个集合**，即：只要两个元素的根节点相同，就视为属于同一个集合。使用树的根节点表示一个集合的方法，称之为「代表元」法。
使用树的根结点**代表**一个集合。

我感觉原来的表述有那么一些歧义，我的理由是：一个结点只能表示它自己。所以我觉得用「代表」会更好一点。

或者说「同在一棵树上的所有结点属于一个集合」。

2020-06-25 08:51 UTC, liweiwei1419 commented on UnionFind/02-template-1.md
> +`Mi`，`Mj` 是亲戚关系代表可以合并 `Mi`，`Mj` 所在的集合。`Pi`，`Pj` 是否具有亲戚关系，只需判断他们是否在同一集合。
这一句 ，改成 、 可能会好一点。而 `Pi`，`Pj` 是否具有亲戚关系，前面加一个 「而」。

2020-06-25 08:57 UTC, liweiwei1419 commented on UnionFind/02-template-1.md
> +先展示代码，细节分析在代码之后。
先展示代码，细节分析在代码之后。

这一句建议去掉。

2020-06-25 08:58 UTC, liweiwei1419 commented on UnionFind/02-template-1.md
> +        /* 查找 x 所在集合的代表元素，即父节点 */
C++ 中的方法注释不知道是不是这样的 /* */ ，我不敢确定，印象中是写在方法上面的。

2020-06-25 09:11 UTC, liweiwei1419 commented on UnionFind/04-template-3.md
> +[1]：[Efficiency of a Good But Not Linear Set Union Algorithm]([http://www.e-maxx.ru/bookz/files/dsu/Efficiency%20of%20a%20Good%20But%20Not%20Linear%20Set%20Union%20Algorithm.%20Tarjan.pdf](http://www
这个链接格式有问题，链接套链接，需要作者确认和修改一下。

2020-06-25 09:14 UTC, liweiwei1419 commented on UnionFind/05-examples.md
> +        int direc[4][2] = {0, 1, 0, -1, 1, 0, -1, 0};
我测试过，这一版代码可以通过测评，但是我个人觉得语义是不清晰的，写成二维的样子会好一点。

我不是很懂 C++，所以也仅供参考。

2020-06-25 09:15 UTC, liweiwei1419 commented on UnionFind/05-examples.md
> +```cpp
并查集的问题代码尽量模块化，封装一下。就这个问题来说，问题不大，取决于作者。

2020-06-25 09:16 UTC, liweiwei1419 commented on UnionFind/05-examples.md
> +该题还可以通过 `DFS` 和 `BFS` 求解，这里不做深入讨论。
「这里不做深入讨论」建议改成「请读者自行完成」。

2020-06-25 09:18 UTC, liweiwei1419 commented on UnionFind/05-examples.md
> +
先写「分析」，再写「代码」可能会好一点，比较符合讲解题目的顺序，建议调整一下。

分析的地方可以分条目叙述，可能观众看起来会比较舒服，这一点取决于作者。

2020-06-25 09:18 UTC, liweiwei1419 commented on UnionFind/05-examples.md
> +```cpp
依然是建议模块化，并且分析在前，代码在后。

2020-06-25 09:23 UTC, liweiwei1419 commented
对一些小的语言表达给了一些建议。

2020-06-26 07:35 UTC, zerotrac requested changes
基本都是些小错误，修改完应该就可以合并啦

2020-06-26 07:35 UTC, zerotrac commented on UnionFind/01-introduction.md
> +并查集（Disjoint set，Union-Find）是一种用来管理元素分组情况的数据结构。并查集的一种高效实现是：**使用树的根节点表示一个集合**，即：只要两个元素的根节点相同，就视为属于同一个集合。使用树的根节点表示一个集合的方法，称之为「代表元」法。
附议。一个集合包含若干个元素，用根节点「代表」一个集合比较合适。同时我也建议说一下集合里的元素之间的关系，例如 weiwei 说的「同在一棵树上的所有结点属于一个集合」

2020-06-26 07:35 UTC, zerotrac commented on UnionFind/01-introduction.md
> +- **查找（Find）**：查找元素所在的集合，即根节点。
大小写要统一

2020-06-26 07:35 UTC, zerotrac commented on UnionFind/01-introduction.md
> +- 集合代表不记录集合成员信息：
建议将「集合代表」改成与上文一致的「代表元」

2020-06-26 07:35 UTC, zerotrac commented on UnionFind/02-template-1.md
> +> 以下 `m` 行：每行两个数 `Mi`，`Mj`，`1<=Mi`，`Mj<=N`，表示 `Mi` 和 `Mj` 具有亲戚关系。
`1 <= Mi, Mj <= N`

2020-06-26 07:35 UTC, zerotrac commented on UnionFind/02-template-1.md
> +        /* 查找 x 所在集合的代表元素，即父节点 */
/* */ 建议写在函数声明的上面一行

2020-06-26 07:35 UTC, zerotrac commented on UnionFind/02-template-1.md
> +        parent = vector<int>(n, 0);
使用 assign 或者 resize

2020-06-26 07:35 UTC, zerotrac commented on UnionFind/02-template-1.md
> +    // freopen("1.txt", "r", stdin);
这行删掉比较好

2020-06-26 07:35 UTC, zerotrac commented on UnionFind/02-template-1.md
> +每次查询节点 `1` 的时候都需要遍历整个「树」，所以 `Find` 函数最坏时间复杂度是：$O(n)$，$n$ 为节点数。
整**棵**树

2020-06-26 07:35 UTC, zerotrac commented on UnionFind/03-template-2.md
> +采用**路径压缩（Path Compression）**进行优化。路径压缩会在执行 `Find(x)` 函数时，将 `x` 到根节点的所有节点全部指向根。由于我们用的是代表元法，树的形态并不重要，路径压缩保证了同一棵树的根结点不变，但是树变的扁平，缩短下次查询时的查找路径。
变得

2020-06-26 07:35 UTC, zerotrac commented on UnionFind/05-examples.md
> +
附议，分析在前比较好

2020-06-26 07:35 UTC, zerotrac commented on UnionFind/05-examples.md
> +```cpp
将并查集单独作为一个 class

2020-06-29 07:20 UTC, liweiwei1419 commented on UnionFind/04-template-3.md
> +[1]：[Efficiency of a Good But Not Linear Set Union Algorithm](http://www.e-maxx.ru/bookz/files/dsu/Efficiency of a Good But Not Linear Set Union Algorithm. Tarjan.pdf)
这个链接空格的地方要编码一下，页面才会显示正确。

```
http://www.e-maxx.ru/bookz/files/dsu/Efficiency%20of%20a%20Good%20But%20Not%20Linear%20Set%20Union%20Algorithm.%20Tarjan.pdf
```

2020-06-29 07:24 UTC, liweiwei1419 commented
URL 部分格式处理一下就可以发布了。

2020-07-03 08:22 UTC, merged